[package]
name = "hive"
version = "0.1.0"
edition = "2021"
authors = ["Konglig Datasektionen"]
description = "Group and permissions management system"
repository = "https://github.com/datasektionen/hive"
license = "MIT"
publish = false

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
log = "0.4.25"
serde = { version = "1.0.218", features = ["derive"] }
simplelog = "0.12.2"
