[package]
name = "hive"
version = "0.1.0"
edition = "2021"
authors = ["Konglig Datasektionen"]
description = "Group and permissions management system"
repository = "https://github.com/datasektionen/hive"
license = "MIT"
publish = false

[dependencies]
anyhow = "1.0.96"
askama = { version = "0.12.1", features = ["with-rocket"] }
askama_rocket = "0.12.0"
clap = { version = "4.5.30", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
log = "0.4.25"
rocket = { version = "0.5.1", features = ["json"] }
rust-i18n = "3.1.3"
serde = { version = "1.0.218", features = ["derive"] }
simplelog = "0.12.2"
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "json",
] }
thiserror = "2.0.11"

[profile.dev.package.askama_derive]
opt-level = 3 # faster incremental compiles
