use_field_init_shorthand = true

# Rustfmt does not support using unstable features in stable Rust, except
# if they are enabled through the CLI (i.e., not this rustfmt.toml) file:
# https://github.com/rust-lang/rustfmt/issues/3387#issuecomment-1867606088
# as such, use this command when necessary: `cargo make fmt-unstable`
# TODO: move these options as they become stable
# TODO: add ignore = ["entity"] when stable; unsettable from CLI args
# -- @@UNSTABLE_BELOW@@ --
# unstable_features = true
# format_code_in_doc_comments = true
# format_generated_files = false
# format_strings = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# normalize_comments = true
# reorder_impl_items = true
# wrap_comments = true
